[package]
name = "biff/one-dependency"
version = "0.1.0"
license = "MIT"
realm = "server"
registry = "https://github.com/dreamcraft-studio/wally-test-index"

[server-dependencies]
Minimal = "biff/minimal@0.1.0"
